
package com;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Magazyn", targetNamespace = "http://magazyn.azu.pk.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Magazyn {


    /**
     * 
     * @param idProjektu
     * @param stan
     */
    @WebMethod
    @RequestWrapper(localName = "umiescProdukt", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.UmiescProdukt")
    @ResponseWrapper(localName = "umiescProduktResponse", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.UmiescProduktResponse")
    @Action(input = "http://magazyn.azu.pk.edu.pl/Magazyn/umiescProduktRequest", output = "http://magazyn.azu.pk.edu.pl/Magazyn/umiescProduktResponse")
    public void umiescProdukt(
        @WebParam(name = "idProjektu", targetNamespace = "")
        int idProjektu,
        @WebParam(name = "stan", targetNamespace = "")
        int stan);

    /**
     * 
     * @param idProjektu
     */
    @WebMethod
    @RequestWrapper(localName = "uzyjForme", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.UzyjForme")
    @ResponseWrapper(localName = "uzyjFormeResponse", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.UzyjFormeResponse")
    @Action(input = "http://magazyn.azu.pk.edu.pl/Magazyn/uzyjFormeRequest", output = "http://magazyn.azu.pk.edu.pl/Magazyn/uzyjFormeResponse")
    public void uzyjForme(
        @WebParam(name = "idProjektu", targetNamespace = "")
        int idProjektu);

    /**
     * 
     * @param idProjektu
     */
    @WebMethod
    @RequestWrapper(localName = "dodajForme", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.DodajForme")
    @ResponseWrapper(localName = "dodajFormeResponse", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.DodajFormeResponse")
    @Action(input = "http://magazyn.azu.pk.edu.pl/Magazyn/dodajFormeRequest", output = "http://magazyn.azu.pk.edu.pl/Magazyn/dodajFormeResponse")
    public void dodajForme(
        @WebParam(name = "idProjektu", targetNamespace = "")
        int idProjektu);

    /**
     * 
     * @param idProjektu
     * @param stan
     * @return
     *     returns com.Projekt
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wezProdukt", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.WezProdukt")
    @ResponseWrapper(localName = "wezProduktResponse", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.WezProduktResponse")
    @Action(input = "http://magazyn.azu.pk.edu.pl/Magazyn/wezProduktRequest", output = "http://magazyn.azu.pk.edu.pl/Magazyn/wezProduktResponse")
    public Projekt wezProdukt(
        @WebParam(name = "idProjektu", targetNamespace = "")
        int idProjektu,
        @WebParam(name = "stan", targetNamespace = "")
        int stan);

    /**
     * 
     * @param ilosc
     */
    @WebMethod
    @RequestWrapper(localName = "wezSurowiec", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.WezSurowiec")
    @ResponseWrapper(localName = "wezSurowiecResponse", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.WezSurowiecResponse")
    @Action(input = "http://magazyn.azu.pk.edu.pl/Magazyn/wezSurowiecRequest", output = "http://magazyn.azu.pk.edu.pl/Magazyn/wezSurowiecResponse")
    public void wezSurowiec(
        @WebParam(name = "ilosc", targetNamespace = "")
        int ilosc);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "zamowSurowiec", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.ZamowSurowiec")
    @ResponseWrapper(localName = "zamowSurowiecResponse", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.ZamowSurowiecResponse")
    @Action(input = "http://magazyn.azu.pk.edu.pl/Magazyn/zamowSurowiecRequest", output = "http://magazyn.azu.pk.edu.pl/Magazyn/zamowSurowiecResponse")
    public void zamowSurowiec();

    /**
     * 
     * @param ilosc
     */
    @WebMethod
    @RequestWrapper(localName = "dodajSurowiec", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.DodajSurowiec")
    @ResponseWrapper(localName = "dodajSurowiecResponse", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.DodajSurowiecResponse")
    @Action(input = "http://magazyn.azu.pk.edu.pl/Magazyn/dodajSurowiecRequest", output = "http://magazyn.azu.pk.edu.pl/Magazyn/dodajSurowiecResponse")
    public void dodajSurowiec(
        @WebParam(name = "ilosc", targetNamespace = "")
        int ilosc);

    /**
     * 
     * @param stan
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "zwrocListeIDProduktow", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.ZwrocListeIDProduktow")
    @ResponseWrapper(localName = "zwrocListeIDProduktowResponse", targetNamespace = "http://magazyn.azu.pk.edu.pl/", className = "com.ZwrocListeIDProduktowResponse")
    @Action(input = "http://magazyn.azu.pk.edu.pl/Magazyn/zwrocListeIDProduktowRequest", output = "http://magazyn.azu.pk.edu.pl/Magazyn/zwrocListeIDProduktowResponse")
    public List<Integer> zwrocListeIDProduktow(
        @WebParam(name = "stan", targetNamespace = "")
        int stan);

}
