
package aznu.webservices.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Magazyn", targetNamespace = "http://magazyn.azu.pk.edu.pl/", wsdlLocation = "http://localhost:9999/Magazyn-1.0-SNAPSHOT/Magazyn?wsdl")
public class Magazyn_Service
    extends Service
{

    private final static URL MAGAZYN_WSDL_LOCATION;
    private final static WebServiceException MAGAZYN_EXCEPTION;
    private final static QName MAGAZYN_QNAME = new QName("http://magazyn.azu.pk.edu.pl/", "Magazyn");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/Magazyn-1.0-SNAPSHOT/Magazyn?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAGAZYN_WSDL_LOCATION = url;
        MAGAZYN_EXCEPTION = e;
    }

    public Magazyn_Service() {
        super(__getWsdlLocation(), MAGAZYN_QNAME);
    }

    public Magazyn_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAGAZYN_QNAME, features);
    }

    public Magazyn_Service(URL wsdlLocation) {
        super(wsdlLocation, MAGAZYN_QNAME);
    }

    public Magazyn_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAGAZYN_QNAME, features);
    }

    public Magazyn_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Magazyn_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Magazyn
     */
    @WebEndpoint(name = "MagazynPort")
    public Magazyn getMagazynPort() {
        return super.getPort(new QName("http://magazyn.azu.pk.edu.pl/", "MagazynPort"), Magazyn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Magazyn
     */
    @WebEndpoint(name = "MagazynPort")
    public Magazyn getMagazynPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://magazyn.azu.pk.edu.pl/", "MagazynPort"), Magazyn.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAGAZYN_EXCEPTION!= null) {
            throw MAGAZYN_EXCEPTION;
        }
        return MAGAZYN_WSDL_LOCATION;
    }

}
