
package aznu.webservices.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoItemFound", targetNamespace = "http://magazyn.azu.pk.edu.pl/")
public class NoItemFound_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoItemFound faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NoItemFound_Exception(String message, NoItemFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NoItemFound_Exception(String message, NoItemFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: aznu.webservices.NoItemFound
     */
    public NoItemFound getFaultInfo() {
        return faultInfo;
    }

}
