
package factory.marles.pl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Factory", targetNamespace = "http://factory.marles.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Factory {


    /**
     * 
     * @param idProjektu
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wykonajForme", targetNamespace = "http://factory.marles.pl/", className = "factory.marles.pl.WykonajForme")
    @ResponseWrapper(localName = "wykonajFormeResponse", targetNamespace = "http://factory.marles.pl/", className = "factory.marles.pl.WykonajFormeResponse")
    @Action(input = "http://factory.marles.pl/Factory/wykonajFormeRequest", output = "http://factory.marles.pl/Factory/wykonajFormeResponse")
    public int wykonajForme(
        @WebParam(name = "ID_Projektu", targetNamespace = "")
        int idProjektu);

    /**
     * 
     * @param idProjektu
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wykonajOdlew", targetNamespace = "http://factory.marles.pl/", className = "factory.marles.pl.WykonajOdlew")
    @ResponseWrapper(localName = "wykonajOdlewResponse", targetNamespace = "http://factory.marles.pl/", className = "factory.marles.pl.WykonajOdlewResponse")
    @Action(input = "http://factory.marles.pl/Factory/wykonajOdlewRequest", output = "http://factory.marles.pl/Factory/wykonajOdlewResponse")
    public boolean wykonajOdlew(
        @WebParam(name = "ID_Projektu", targetNamespace = "")
        int idProjektu);

    /**
     * 
     * @param idProjektu
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "szlifuj", targetNamespace = "http://factory.marles.pl/", className = "factory.marles.pl.Szlifuj")
    @ResponseWrapper(localName = "szlifujResponse", targetNamespace = "http://factory.marles.pl/", className = "factory.marles.pl.SzlifujResponse")
    @Action(input = "http://factory.marles.pl/Factory/szlifujRequest", output = "http://factory.marles.pl/Factory/szlifujResponse")
    public boolean szlifuj(
        @WebParam(name = "ID_Projektu", targetNamespace = "")
        int idProjektu);

    /**
     * 
     * @param idProjektu
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "maluj", targetNamespace = "http://factory.marles.pl/", className = "factory.marles.pl.Maluj")
    @ResponseWrapper(localName = "malujResponse", targetNamespace = "http://factory.marles.pl/", className = "factory.marles.pl.MalujResponse")
    @Action(input = "http://factory.marles.pl/Factory/malujRequest", output = "http://factory.marles.pl/Factory/malujResponse")
    public boolean maluj(
        @WebParam(name = "ID_Projektu", targetNamespace = "")
        int idProjektu);

}
