
package factory.marles.pl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Factory", targetNamespace = "http://factory.marles.pl/", wsdlLocation = "http://localhost:17952/Factory/Factory?WSDL")
public class Factory_Service
    extends Service
{

    private final static URL FACTORY_WSDL_LOCATION;
    private final static WebServiceException FACTORY_EXCEPTION;
    private final static QName FACTORY_QNAME = new QName("http://factory.marles.pl/", "Factory");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:17952/Factory/Factory?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FACTORY_WSDL_LOCATION = url;
        FACTORY_EXCEPTION = e;
    }

    public Factory_Service() {
        super(__getWsdlLocation(), FACTORY_QNAME);
    }

    public Factory_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FACTORY_QNAME, features);
    }

    public Factory_Service(URL wsdlLocation) {
        super(wsdlLocation, FACTORY_QNAME);
    }

    public Factory_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FACTORY_QNAME, features);
    }

    public Factory_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Factory_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Factory
     */
    @WebEndpoint(name = "FactoryPort")
    public Factory getFactoryPort() {
        return super.getPort(new QName("http://factory.marles.pl/", "FactoryPort"), Factory.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Factory
     */
    @WebEndpoint(name = "FactoryPort")
    public Factory getFactoryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://factory.marles.pl/", "FactoryPort"), Factory.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FACTORY_EXCEPTION!= null) {
            throw FACTORY_EXCEPTION;
        }
        return FACTORY_WSDL_LOCATION;
    }

}
